#!/usr/bin/env bash
########################################################################
#    File Name: CREATE_USER.sh
# 
#       Author: lingren Shanghai,Inc.
#         Mail: shuiheng_40@163.com
# Created Time: 2016年05月05日 星期四 11时10分29秒
#  Description: ...
# 
########################################################################
set -u

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
GRAY="\033[0;37m"
LIGHT_RED="\033[1;31m"
LIGHT_YELLOW="\033[1;33m"
LIGHT_GREEN="\033[1;32m"
LIGHT_BLUE="\033[0;34m"
LIGHT_GRAY="\033[1;37m"
END="\033[0;00m"

function check_user_exist()
{
    local user_name=$1
    id ${user_name} >& /dev/null
    return $?
}

function print_help_info()
{
    echo -e "${RED}Usage: ${END}"
    echo -e "\t${YELLOW}CREATE_USER user_name [home_path]${END}"
}

DEFAULT_SHELL=/bin/bash
DEFAULT_HOME_PATH=/data


if [ $# -eq 1 ];then
    ARG=$1
    if [ $ARG = "-h" ] || [ $ARG = "-H" ] || [ $ARG = "--help" ];then
        print_help_info
        exit 0
    fi

    USER_NAME=$1
    echo -e "${GREEN}使用默认HOME目录:${YELLOW}${DEFAULT_HOME_PATH}${END}"
elif [ $# -eq 2 ];then
    USER_NAME=$1
    DEFAULT_HOME_PATH=$2
else
    print_help_info
    exit 1
fi

echo -e "${GREEN}创建的用户目录:${YELLOW}${DEFAULT_HOME_PATH}/${USER_NAME}"
echo -e "${GREEN}用户默认SH:${YELLOW}${DEFAULT_SHELL}"
echo -e "${GREEN}是否确认创建用户 ${YELLOW}${USER_NAME}${GREEN}?${YELLOW}Y/N(Y)${END}"
read choice
if [ "${choice}" = "N" ] || [ "${choice}" = "n" ];then
    echo -e "${RED}取消创建用户!!${END}"
    exit 0
else
    echo -e "${GREEN}开始创建用户${END}"
fi

check_user_exist ${USER_NAME}
ret=$?
if [ $ret -eq 0 ];then
    echo -e "${RED}用户${YELLOW}${USER_NAME}${RED}已存在,创建用户失败!!${END}"
    exit 1
fi

useradd -d ${DEFAULT_HOME_PATH}/${USER_NAME} -m ${USER_NAME} -s ${DEFAULT_SHELL}

echo -e "${GREEN}完成创建用户${END}"
#去除其他用户对该目录的访问权限
chmod -R o-rx ${DEFAULT_HOME_PATH}/${USER_NAME}

echo -e "${GREEN}是否修改用户 ${YELLOW}${USER_NAME}${GREEN}的密码?${YELLOW}Y/N(Y)${END}"
read choice
if [ "${choice}" = "N" ] || [ "${choice}" = "n" ];then
    echo -e "${RED}取消修改用户密码!!${END}"
    exit 0
else
    echo -e "${GREEN}开始修改用户密码${END}"
fi

passwd ${USER_NAME}

echo -e "${GREEN}完成修改用户密码${END}"

