#!/usr/bin/env bash
########################################################################
#    File Name: DELETE_USER.sh
# 
#       Author: lorishui
#         Mail: shuiheng_40@163.com
# Created Time: 2016年05月05日 星期四 12时36分06秒
#  Description: ...
# 
########################################################################
set -u

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
GRAY="\033[0;37m"
LIGHT_RED="\033[1;31m"
LIGHT_YELLOW="\033[1;33m"
LIGHT_GREEN="\033[1;32m"
LIGHT_BLUE="\033[0;34m"
LIGHT_GRAY="\033[1;37m"
END="\033[0;00m"

function check_user_exist()
{
    local user_name=$1
    id ${user_name} >& /dev/null
    return $?
}

function print_help_info()
{
    echo -e "${RED}Usage: ${END}"
    echo -e "\t${YELLOW}DELETE_USER user_name [home_path]${END}"
}

DEFAULT_HOME_PATH=/data

if [ $# -eq 1 ];then
    ARG=$1
    if [ $ARG = "-h" ] || [ $ARG = "-H" ] || [ $ARG = "--help" ];then
        print_help_info
        exit 0
    fi

    USER_NAME=$1
    echo -e "${GREEN}使用默认HOME目录:${YELLOW}${DEFAULT_HOME_PATH}${END}"
elif [ $# -eq 2 ];then
    USER_NAME=$1
    DEFAULT_HOME_PATH=$2
else
    print_help_info
    exit 1
fi

echo -e "${GREEN}需删除的用户目录:${YELLOW}${DEFAULT_HOME_PATH}/${USER_NAME}"
echo -e "${GREEN}是否删除用户 ${YELLOW}${USER_NAME}${GREEN}?${YELLOW}Y/N(Y)${END}"
read choice
if [ "${choice}" = "N" ] || [ "${choice}" = "n" ];then
    echo -e "${RED}取消删除用户!!${END}"
    exit 0
else
    echo -e "${GREEN}开始删除用户${END}"
fi

check_user_exist ${USER_NAME}
ret=$?
if [ $ret -ne 0 ];then
    echo -e "${RED}用户${YELLOW}${USER_NAME}${RED}不存在,删除用户失败!!${END}"
    exit 1
fi

if [ ! -d "${DEFAULT_HOME_PATH}/${USER_NAME}" ];then
    echo -e "${RED}用户目录${YELLOW}${DEFAULT_HOME_PATH}/${USER_NAME}${RED}不存在${END}"
    exit 1
fi

userdel ${USER_NAME}

chmod -R ugo-rwx ${DEFAULT_HOME_PATH}/${USER_NAME}
chown -R root:root ${DEFAULT_HOME_PATH}/${USER_NAME}

echo -e "${GREEN}完成删除用户${END}"
echo -e "${YELLOW}特别说明:${END}"
echo -e "${YELLOW}目录:${RED}${DEFAULT_HOME_PATH}/${USER_NAME} ${YELLOW}未进行删除,如需删除请手动删除.${END}"
