#!/usr/bin/env bash
########################################################################
#    File Name: Lock_Dir.sh
# 
#       Author: lingren Shanghai,Inc.
#         Mail: shuiheng_40@163.com
# Created Time: Tue 31 May 2016 10:40:14 AM CST
#  Description: ...
# 
########################################################################
set -u

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
GRAY="\033[0;37m"
LIGHT_RED="\033[1;31m"
LIGHT_YELLOW="\033[1;33m"
LIGHT_GREEN="\033[1;32m"
LIGHT_BLUE="\033[0;34m"
LIGHT_GRAY="\033[1;37m"
END="\033[0;00m"

function print_help()
{
    echo -e "${YELLOW}usage:${END}"
    echo -e "\t${YELLOW}$0 lock/unlock lock_dir/unlock_file${END}"
}


function lock_dir()
{
    dir_path=$1
    dir_name=${dir_path##*/}
    echo -e "${GREEN}是否确认对目录 ${YELLOW}${dir_path} ${GREEN}进行加密?${YELLOW}Y/N(N)${END}"
    read choice
    if [ "${choice}" = "Y" ] || [ "${choice}" = "y" ];then
        echo -e "${YELLOW}请输入文件夹加密密码:${END}"
        read -s passwd
        echo -e "${YELLOW}请再次输入文件夹加密密码:${END}"
        read -s repeatpasswd
        if [ "${passwd}" != "${repeatpasswd}" ];then
            echo -e "${RED}两次输入的密码不一致!!${END}"
            echo -e "${YELLOW}退出脚本执行!${END}"
            exit 1
        fi

    else
        echo -e "${YELLOW}退出脚本执行!${END}"
        exit 0
    fi

    tar -zcvf - ${dir_path}|openssl des3 -salt -k ${passwd} | dd of=${dir_name}.des3
}

function unlock_dir()
{
    unlock_file_path=$1
    echo -e "${GREEN}是否确认对文件 ${YELLOW}${unlock_file_path} ${GREEN}进行解密?${YELLOW}Y/N(N)${END}"
    read choice
    if [ "${choice}" = "Y" ] || [ "${choice}" = "y" ];then
        echo -e "${YELLOW}请输入文件夹解密密码:${END}"
        read -s passwd
    else
        echo -e "${YELLOW}退出脚本执行!${END}"
        exit 0
    fi
    dd if=${unlock_file_path} |openssl des3 -d -k ${passwd}|tar zxf - 1>&- 2>&-
    ret=$?
    if [ ${ret} != 0 ];then
        echo -e "${RED}密码错误,解密文件失败!!${END}"
        exit 1
    fi
    echo -e "${GREEN}解密文件成功!!${END}"
}

#read -s content
#echo $content

proc_type_array=('lock', 'unlock')

if [ $# -eq 2 ];then
    argv1=$1
    argv2=$2
    case ${argv1} in
        lock)
            lock_dir $argv2
            ;;
        unlock)
            unlock_dir $argv2
            ;;
        *)
            echo -e "${RED}脚本参数 ${YELLOW}${argv1} ${RED}错误${END}"
            print_help
            exit 1
            ;;
    esac
else
    echo -e "${RED}脚本参数错误${END}"
    print_help
    exit 1
fi
