#!/usr/bin/env bash
########################################################################
#    File Name: SVN_COMMIT_EX
# 
#       Author: lorishui
#         Mail: shuiheng_40@163.com
# Created Time: Tue 02 Jun 2015 09:27:30 AM CST
#  Description: ...
# 
########################################################################
set -u

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
GRAY="\033[0;37m"
LIGHT_RED="\033[1;31m"
LIGHT_YELLOW="\033[1;33m"
LIGHT_GREEN="\033[1;32m"
LIGHT_BLUE="\033[0;34m"
LIGHT_GRAY="\033[1;37m"
END="\033[0;00m"

NOW_DIR=`pwd`

function check_is_svn_dir()
{
    local is_svn_dir=`svn info | grep "URL:" | wc -l`
    if [ $is_svn_dir -eq 0 ];then
        return 0
    fi
    return 1
}

function check_is_has_new_file()
{
    local new_file_list=`svn status | grep ^? | grep -v tags | awk '{print $2}'`
    if [ ${#new_file_list} -gt 0 ];then
        return 1
    fi
    return 0
}

function check_is_need_commit()
{
    local new_file_list=`svn status | grep -v ^? | awk '{print $2}'`
    if [ ${#new_file_list} -gt 0 ];then
        return 1
    fi
    return 0
}

function add_new_file_to_svn()
{
    local new_file_list=`svn status | grep ^? | grep -v tags | awk '{print $2}'`
    if [ ${#new_file_list} -eq 0 ];then
        dialog --title "警告" --backtitle "${backtitle}" --msgbox "添加文件列表为空,添加失败!" 10 50 
        return 
    fi
    local tmp_file=.svn_tmp
    local new_file=svn_tmp
    svn status | grep ^? | grep -v tags | awk '{print $2}' > ${tmp_file}
    local file_list=`cat ${tmp_file} | xargs echo`
    local ret=0

    content=""
    index=1
    for file in ${file_list}
    do
        content=${content}"${file} ${index} on "
        let index++
    done
    dialog --title "新增文件列表" --backtitle "${backtitle}" --checklist "列表" 20 100 100\
        ${content} 2> ${new_file}
    add_file_list=`cat ${new_file} | xargs echo`
    if [ -z ${add_file_list} ];then
        ret=1
    else
        dialog --title "提示" --backtitle "${backtitle}" --no-shadow --yesno "是否确认添加文件到SVN?" 10 50
        if [ $? == 0 ];then
            svn add ${add_file_list}
            echo ${add_file_list}
            ret=0
        else
            dialog --title "警告" --backtitle "${backtitle}" --msgbox "取消添加文件!" 10 30 
            ret=1
        fi
        rm -rf ${new_file}
    fi
    rm -rf ${tmp_file} 
    return ${ret}
}

function commit_file_to_svn()
{
    local new_file_list=`svn status | grep -v ^? | awk '{print $2}'`
    if [ ${#new_file_list} -eq 0 ];then
        dialog --title "警告" --backtitle "${backtitle}" --msgbox "变更文件列表为空,提交失败!" 10 50 
        return 
    fi
    local tmp_file=.svn_tmp
    local new_file=svn_tmp
    svn status | grep -v ^? | grep -v ${tmp_file} | awk '{print $2}' > ${tmp_file}
    local file_list=`cat ${tmp_file} | xargs echo`
    local ret=0

    content=""
    index=1
    for file in ${file_list}
    do
        content=${content}"${file} ${index} on "
        let index++
    done
    dialog --title "变更文件列表" --backtitle "${backtitle}" --checklist "列表" 20 100 100\
        ${content} 2> ${new_file}
    commit_file_list=`cat ${new_file} | xargs echo`
    if [ -z ${commit_file_list} ];then
        ret=1
    else
        dialog --title "提示" --backtitle "${backtitle}" --no-shadow --yesno "是否确认提交文件到SVN?" 10 50
        if [ $? == 0 ];then
            svn commit ${commit_file_list}
            ret=0
        else
            dialog --title "警告" --backtitle "${backtitle}" --infobox "取消提交文件!" 10 30 ; sleep 1
            ret=1
        fi
        rm -rf ${new_file}
    fi
    rm -rf ${tmp_file} 
    return ${ret}
}
backtitle="SVN_COMMIT_EX"

check_is_svn_dir
ret=$?
if [ $ret -eq 0 ];then
   dialog --title "错误" --backtitle "${backtitle}" --msgbox "目录错误,本目录未包含svn信息!" 10 50
   dialog --clear
   clear
   exit 1
fi

check_is_has_new_file
ret=$?
if [ $ret -gt 0 ];then
    dialog --title "提示" --backtitle "${backtitle}" --no-shadow --yesno "发现有新文件未加入svn,是否进行添加?" 10 50
    if [ $? == 0 ];then
        add_new_file_to_svn
        ret=$?
        if [ $ret -gt 0 ];then
            dialog --title "提示" --backtitle "${backtitle}" --no-shadow --yesno "未成功添加新文件,是否继续?" 10 50
            if [ $? == 0 ];then
                :
            else
                dialog --title "提示" --backtitle "${backtitle}" --no-shadow --msgbox "添加文件失败,脚本退出!!" 10 50
                dialog --clear
                clear
                exit 1
            fi
        else
            dialog --title "提示" --backtitle "${backtitle}" --no-shadow --infobox "添加新文件成功!" 10 50 ; sleep 1
        fi
    else
        dialog --title "提示" --backtitle "${backtitle}" --no-shadow --infobox "不对新文件进行处理!" 10 50 ; sleep 1
    fi
fi

check_is_need_commit
ret=$?
if [ $ret -gt 0 ];then
    dialog --title "提示" --backtitle "${backtitle}" --no-shadow --yesno "发现有文件变更,是否进行提交?" 10 50
    if [ $? == 0 ];then
        commit_file_to_svn
        ret=$?
        if [ $ret -gt 0 ];then
            dialog --title "警告" --backtitle "${backtitle}" --no-shadow --msgbox "未成功提交文件!" 10 30
        else
            dialog --title "提示" --backtitle "${backtitle}" --no-shadow --msgbox "成功提交文件!" 10 30
        fi
    else
        dialog --title "提示" --backtitle "${backtitle}" --no-shadow --msgbox "不对变更文件进行提交处理!" 10 30
    fi
else
    dialog --title "提示" --backtitle "${backtitle}" --no-shadow --msgbox "未发现变更的文件,脚本退出!" 10 30
fi

dialog --clear
clear
exit 0
