#!/usr/bin/env bash
########################################################################
#    File Name: SVN_ST.sh
# 
#       Author: 
#         Mail: shuiheng_40@163.com
# Created Time: Tue 02 Jun 2015 09:27:30 AM CST
#  Description: ...
# 
########################################################################
set -u

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[0;33m"
GRAY="\033[0;37m"
LIGHT_RED="\033[1;31m"
LIGHT_YELLOW="\033[1;33m"
LIGHT_GREEN="\033[1;32m"
LIGHT_BLUE="\033[0;34m"
LIGHT_GRAY="\033[1;37m"
END="\033[0;00m"

NOW_DIR=`pwd`

function check_is_svn_dir()
{
    local is_svn_dir=`svn info | grep "URL:" | wc -l`
    if [ $is_svn_dir -eq 0 ];then
        return 0
    fi
    return 1
}

function check_is_has_new_file()
{
    local new_file_list=`svn status | grep ^? | awk '{print $2}'`
    if [ ${#new_file_list} -gt 0 ];then
        return 1
    fi
    return 0
}

function check_is_need_commit()
{
    local new_file_list=`svn status | grep -v ^? | awk '{print $2}'`
    if [ ${#new_file_list} -gt 0 ];then
        return 1
    fi
    return 0
}

function add_new_file_to_svn()
{
    local new_file_list=`svn status | grep ^? | awk '{print $2}'`
    if [ ${#new_file_list} -eq 0 ];then
        echo -e "${RED}添加文件列表为空,添加失败!${END}"
        return 
    fi
    local tmp_file=.svn_tmp
    local new_file=svn_tmp
    svn status | grep ^? | grep -v ${tmp_file} | awk '{print $2}' > ${tmp_file}
    vi -n ${new_file} -c "+r ${tmp_file}"
    local ret=0
    if [ ! -f ${new_file} ];then
        ret=1
    else
        cat ${new_file}
        echo -e "${YELLOW}是否确认添加上面的文件?Y/N(N)${END}"
        read choose
        if [ "${choose}" = "Y" ] || [ "${choose}" = "y" ];then
            local add_str=`cat ${new_file} | xargs echo` 
            svn add ${add_str}
            ret=0
        else
            echo -e "${RED}取消添加文件!${END}"
            ret=1
        fi
        rm -rf ${new_file}
    fi
    rm -rf ${tmp_file} 
    return ${ret}
}

function commit_file_to_svn()
{
    local new_file_list=`svn status | grep -v ^? | awk '{print $2}'`
    if [ ${#new_file_list} -eq 0 ];then
        echo -e "${RED}变更文件列表为空,提交失败!${END}"
        return 
    fi
    local tmp_file=.svn_tmp
    local new_file=svn_tmp
    svn status | grep -v ^? | grep -v ${tmp_file} | awk '{print $2}' > ${tmp_file}
    vi -n ${new_file} -c "+r ${tmp_file}"
    local ret=0
    if [ ! -f ${new_file} ];then
        ret=1
    else
        cat ${new_file}
        echo -e "${YELLOW}是否确认提交上面的文件?Y/N(N)${END}"
        read choose
        if [ "${choose}" = "Y" ] || [ "${choose}" = "y" ];then
            local commit_str=`cat ${new_file} | xargs echo` 
            svn commit ${commit_str}
            ret=0
        else
            echo -e "${RED}取消提交文件!${END}"
            ret=1
        fi
        rm -rf ${new_file}
    fi
    rm -rf ${tmp_file} 
    return ${ret}

}

check_is_svn_dir
ret=$?
if [ $ret -eq 0 ];then
   echo -e "${RED}${NOW_DIR}目录错误,本目录未包含svn信息!${END}" 
   exit 1
fi

check_is_has_new_file
ret=$?
if [ $ret -gt 0 ];then
    echo -e "${GREEN}发现有新文件未加入svn,是否进行添加?Y/N(Y)${END}"
    read choose
    if [ "${choose}" = "Y" ] || [ "${choose}" = "y" ] || [ -z "${choose}" ];then
        add_new_file_to_svn
        ret=$?
        if [ $ret -gt 0 ];then
            echo -e "${YELLOW}未成功添加新文件,是否继续?Y/N(Y)${END}"
            read choose
            if [ "${choose}" = "Y" ] || [ "${choose}" = "y" ] || [ -z "${choose}" ];then
                :
            else
                echo -e "${RED}添加文件失败,脚本退出!!${END}"
                exit 1
            fi
        else
            echo -e "${GREEN}添加新文件成功!${END}"
        fi
    else
        echo -e "${YELLOW}不对新文件进行处理!${END}"
    fi
fi

check_is_need_commit
ret=$?
if [ $ret -gt 0 ];then
    echo -e "${GREEN}发现有文件变更,是否进行提交?Y/N(Y)${END}"
    read choose
    if [ "${choose}" = "Y" ] || [ "${choose}" = "y" ] || [ -z "${choose}" ];then
        commit_file_to_svn
        ret=$?
        if [ $ret -gt 0 ];then
            echo -e "${YELLOW}未成功提交文件!${END}"
        else
            echo -e "${GREEN}成功提交文件!${END}"
        fi
    else
        echo -e "${YELLOW}不对变更文件进行提交处理!${END}"
    fi
else
    echo -e "${GREEN}未发现变更的文件!${END}"
fi

exit 0
